module.exports = {
  apps: [
    {
      name: "http-checker",
      script: "/home/netit972/crawling-app/venv/bin/python3",
      args: "-m modules.http_checker",
      cwd: "/home/netit972/crawling-app",
      interpreter: "none",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        PYTHONPATH: "/home/netit972/crawling-app",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "/home/netit972/crawling-app/logs/pm2-http-checker.log",
      error_file: "/home/netit972/crawling-app/logs/pm2-http-checker-error.log",
      out_file: "/home/netit972/crawling-app/logs/pm2-http-checker-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "crawler",
      script: "/home/netit972/crawling-app/venv/bin/python3",
      args: "-m modules.crawler",
      cwd: "/home/netit972/crawling-app",
      interpreter: "none",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 10000,
      env: {
        PYTHONPATH: "/home/netit972/crawling-app",
        PYTHONUNBUFFERED: "1",
        LD_LIBRARY_PATH: "/home/netit972/crawling-app/libs",
      },
      log_file: "/home/netit972/crawling-app/logs/pm2-crawler.log",
      error_file: "/home/netit972/crawling-app/logs/pm2-crawler-error.log",
      out_file: "/home/netit972/crawling-app/logs/pm2-crawler-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "siretisation",
      script: "/home/netit972/crawling-app/venv/bin/python3",
      args: "-m modules.siretisation",
      cwd: "/home/netit972/crawling-app",
      interpreter: "none",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 10000,
      env: {
        PYTHONPATH: "/home/netit972/crawling-app",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "/home/netit972/crawling-app/logs/pm2-siretisation.log",
      error_file: "/home/netit972/crawling-app/logs/pm2-siretisation-error.log",
      out_file: "/home/netit972/crawling-app/logs/pm2-siretisation-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "dashboard",
      script: "/home/netit972/crawling-app/venv/bin/gunicorn",
      args: "--bind 0.0.0.0:5051 --workers 2 --timeout 300 modules.dashboard:app",
      cwd: "/home/netit972/crawling-app",
      interpreter: "none",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        PYTHONPATH: "/home/netit972/crawling-app",
        PYTHONUNBUFFERED: "1",
      },
      log_file: "/home/netit972/crawling-app/logs/pm2-dashboard.log",
      error_file: "/home/netit972/crawling-app/logs/pm2-dashboard-error.log",
      out_file: "/home/netit972/crawling-app/logs/pm2-dashboard-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};